src/Nowruz/modules/Auth/containers/signin/SignInForm/useSignInForm.tsx
src/Nowruz/pages/forget-password/email.tsx

if users enters less than 8 character password, login API returns an error different from 'not matched' which was not handled in UI

fix login error message

---

src/Nowruz/pages/oauth/google.tsx

**Ticket:** [Login with the Google account that is not registered on Socious, should proceed to talent sign-up](https://www.notion.so/socious/Login-with-the-Google-account-that-is-not-registered-on-Socious-should-proceed-to-talent-sign-up-4fff1fee9e784a399dbe1ceb3b77755b?pvs=4)
**Description:**
- Change the redirect path once successfully authorised from Google
**Media:**
https://github.com/socious-io/web-app-v2/assets/5590282/8d8ee7ca-133f-4017-bf4a-05be2daed26a

chore: change the redirect page if user has not been registered

---

.gitignore
.storybook/main.ts
package-lock.json
package.json
src/Nowruz/modules/general/components/BackLink/index.tsx
src/Nowruz/modules/general/components/SearchDropdown/index.tsx
src/Nowruz/modules/general/components/iconDropDown/index.tsx
src/stories/button.stories.tsx

**Ticket:** [Add Accessibility Addon to Storybook](https://www.notion.so/socious/Add-Accessibility-Addon-to-Storybook-39a7cef6faae4761bef0e1fb6a36b58c?pvs=4)
**Description:**
- Added a11y add-on in the storybook so that we will be able to check locally the accessibility.
- Also addressed some of the common a11y violations we have right now in our components
**Media**
Accessibility addon:
Some _Violations_ that have been resolved:

add a11y addon into storybook

---

node_modules/.package-lock.json
src/Nowruz/modules/general/components/countryFlag/countryFlag.module.scss
src/Nowruz/modules/general/components/countryFlag/index.tsx
src/Nowruz/modules/general/utils/index.ts
src/Nowruz/modules/userProfile/components/about/about.module.scss
src/Nowruz/modules/userProfile/components/about/certificate/certificates.tsx
src/Nowruz/modules/userProfile/components/about/education/educations.tsx
src/Nowruz/modules/userProfile/components/about/recommendaion/recommendation.tsx
src/Nowruz/modules/userProfile/components/about/summary.tsx
src/Nowruz/modules/userProfile/components/location/index.tsx
src/Nowruz/modules/userProfile/components/mainInfo/index.tsx
src/Nowruz/modules/userProfile/components/mainInfo/mainInfo.module.scss
src/Nowruz/modules/userProfile/components/profileHeader/desktopHeader.tsx
src/Nowruz/modules/userProfile/components/profileHeader/profileHeader.module.scss
src/Nowruz/modules/userProfile/components/website/index.tsx
src/Nowruz/modules/userProfile/components/website/website.module.scss
src/Nowruz/pages/orgProfile/index.tsx
src/stories/chip.stories.tsx

https://github.com/socious-io/web-app-v2/assets/5590282/2c1cd651-f987-4c5d-bf28-c20b6bc19f9a

fix: rejected by qa about tab fixes

---

src/Nowruz/modules/Auth/containers/signup/UserDetails/index.tsx

**Ticket:** [Filled username in sign-up screen: Username is unavailable](https://www.notion.so/socious/Filled-username-in-sign-up-screen-Username-is-unavailable-8c94c66a338f4db0bf6055d04111b79a?pvs=4)
**Description:**
- Remove the prefilled username if accounts are using gmail
https://github.com/socious-io/web-app-v2/assets/5590282/780d1a32-3ff9-461f-86e5-46690eff50a2

chore: remove pre filled username

---

src/Nowruz/modules/userProfile/components/mainInfo/index.tsx
src/Nowruz/modules/userProfile/containers/editInfoOrg/index.tsx
src/Nowruz/modules/userProfile/containers/editInfoOrg/useEditInfoOrg.tsx

This PR is related to this ticket, item 8
https://www.notion.so/socious/Nowruz-Other-org-s-profile-About-tab-excluding-all-other-tabs-e659494dfdf24a9bb36abe8c8707ea39
After checking the code realized that data can be displayed in the profile properly, but since the fields are null, nothing is displayed. To fix the issue checked the 'update component' and added company size field to 'update form', so this field could be modified and then displayed in the profile

Updated edit org component to make size editable

---

src/Nowruz/modules/settings/components/leaveDeleteMember/index.tsx

**FIX:**
- camel case instead of upper case in button issue related to overwriting `classname`

TAS-1448/Fix-Text-Button

---

src/Nowruz/pages/jobs/List/list.module.scss

TAS-1724/Extra-Width-Mobile

---

src/Nowruz/modules/Disputes/DisputesList/index.tsx
src/Nowruz/modules/Disputes/InvitationsList/index.module.scss
src/Nowruz/modules/Disputes/InvitationsList/index.tsx
src/Nowruz/modules/Disputes/InvitationsList/index.types.ts
src/Nowruz/modules/Disputes/InvitationsList/useInvitationsList.tsx
src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx
src/Nowruz/pages/contribute/contributeCenter/contributeCenter.module.scss
src/Nowruz/pages/contribute/contributeCenter/index.tsx
src/Nowruz/pages/contribute/contributeCenter/useContributeCenter.tsx
src/core/api/disputes/disputes.api.ts
src/core/api/disputes/disputes.types.ts
src/core/router/router.blueprint.tsx

**This branch is mainly related to contribute sub category pages.**
TODO:

TAS-1601/Dispute-Resolution-Center-Page

---

src/Nowruz/modules/layout/components/navBar/index.tsx
src/Nowruz/modules/layout/index.tsx
src/core/hooks/useHideScrollbar.tsx

TAS-1663/Fix-Shifting-Background

---

src/Nowruz/modules/contract/components/initiateDisputeModal/successInitiateDispute/index.tsx
src/Nowruz/modules/contract/components/respondDisputeModal/successRespondDispute/index.tsx
src/Nowruz/modules/general/components/Snackbar/index.tsx
src/Nowruz/modules/general/components/Snackbar/index.types.ts
src/Nowruz/pages/feeds/index.tsx

Tas 2071/Fix-Submit-Success-Dispute

---

src/Nowruz/modules/general/components/threeDotButton/index.tsx
src/Nowruz/modules/general/components/threeDotButton/threeDotButton.module.scss

TAS-2069/Fix-Contract-Submenu-Style

---

src/Nowruz/modules/dispute/components/timelineItem/index.tsx

TAS-2168/Fix-Timeline-Dispute-Detail

---

public/icons/circle-tick-white.svg
src/constants/PREFERENCES.ts
src/core/api/users/users.api.ts
src/core/api/users/users.types.ts
src/core/router/router.blueprint.tsx
src/modules/Preferences/OrgPreferences/CultureAccordions/index.module.scss
src/modules/Preferences/OrgPreferences/CultureAccordions/index.tsx
src/modules/Preferences/OrgPreferences/CultureAccordions/index.types.ts
src/modules/Preferences/OrgPreferences/CultureAccordions/useCultureAccordions.tsx
src/modules/Preferences/OrgPreferences/Toggles/index.module.scss
src/modules/Preferences/OrgPreferences/Toggles/index.tsx
src/modules/Preferences/OrgPreferences/Toggles/index.types.ts
src/modules/Preferences/OrgPreferences/Toggles/useToggles.tsx
src/modules/Preferences/OrgPreferences/index.module.scss
src/modules/Preferences/OrgPreferences/index.tsx
src/modules/Preferences/OrgPreferences/useOrgPreferences.tsx
src/modules/general/components/RadioGroup/RadioGroup.types.ts
src/modules/general/components/RadioGroup/index.tsx
src/modules/userProfile/components/about/Culture/index.tsx
src/modules/userProfile/components/about/Culture/index.types.ts
src/modules/userProfile/components/about/index.tsx
src/modules/userProfile/components/about/useAbout.tsx
src/pages/orgProfile/useOrgProfile.tsx

**This PR includes three parts in the org Profile:**
**Also some refactorings on:**
**TODO:**

TAS-2192-TAS-2249/OP-Preferences-Culture

---

src/modules/credentials/educationDetails/useEducationDetails.tsx
src/modules/userProfile/components/about/certificate/certificates.tsx
src/modules/userProfile/containers/createUpdateCertificate/index.tsx
src/modules/userProfile/containers/createUpdateCertificate/useCreateUpdateCertificate.tsx
src/modules/userProfile/containers/verifyEducationModal/useVerifyEducationModal.tsx

**FIX:**
- verify education
- detail of education
- add/edit certificate
we shouldn't put `certificate && <CreateUpdateCertificate {...props} />` because this modal is for adding and editing certificates, and we don't have certificate properties in adding version of the modal.

TAS-2349/Fix-Date-Error

---

src/modules/general/components/horizontalTabs/horizontalTabs.types.ts
src/modules/general/components/horizontalTabs/index.tsx
src/pages/contribute/contributeCenter/index.tsx
src/pages/disputes/index.tsx
src/pages/orgProfile/index.tsx
src/pages/orgProfile/useOrgProfile.tsx

TAS-2438/Refactoring-Horizontal-Tabs

---

src/pages/jobs/List/index.tsx

TAS-641/Fix-Org-Jobs-Page

---

src/pages/jobs/detail/applicants/applicant.tsx

TAS-2418/Whitespace

---

src/modules/chats/components/chatDetailItem/chatDetailItem.types.ts
src/modules/chats/components/chatDetailItem/index.tsx
src/modules/chats/components/chatDetails/index.tsx
src/modules/chats/components/chatDetails/useChatDetails.ts
src/modules/chats/components/summaryCard/index.tsx
src/modules/general/components/avatar/avatar.types.ts
src/modules/general/components/avatarLabelGroup/avatarLabelGroup.types.ts
src/modules/general/components/avatarLabelGroup/index.tsx
src/modules/general/utils/index.ts
src/modules/userProfile/components/about/summary.tsx
src/pages/jobs/detail/applicants/applicant.tsx

**This branch is related to adding a profile click on the chats section on:**
**Also,** includes:

TAS-101/Profile-Click-Chats

---

src/modules/Disputes/DisputesList/index.tsx
src/modules/contract/components/initiateDisputeModal/index.tsx
src/modules/contract/components/initiateDisputeModal/useInitiateDisputeModal.tsx
src/modules/dispute/components/contributorDashboard/index.tsx
src/modules/dispute/components/timelineItem/index.tsx
src/modules/dispute/components/timelineItem/useTimelineItem.tsx
src/modules/general/components/fileUploaderMultiple/useFileUploaderMultiple.tsx
src/modules/layout/containers/notifications/useNotifications.tsx
src/pages/disputes/disputeDetail/useDisputeDetail.tsx
src/pages/disputes/index.tsx
src/pages/disputes/useDisputes.tsx

**This branch is related to some issues on dispute resolution,** includes:

TAS-246/Dispute-Designer-Feedback

---

src/modules/layout/containers/notifications/useNotifications.tsx

TAS-3475/Feeds-Notifications

---

src/constants/constants.ts
src/core/hooks/useSwitchLanguage.tsx
src/core/translation/i18n.ts
src/modules/settings/components/Language/useLanguage.tsx

**This branch is related to handling the default language setting as the user's browser language.**

TAS-4086/Default-Browser-Language
