src/core/http.ts
…h and use production base URL
Change it in anyway you like to setup this kind of config variables for different env
=> alpha switch to production data

public/icons/close-white.svg, public/icons/info.svg, src/components/atoms/toggle/index.tsx, src/components/atoms/toggle/toggle.module.scss, src/components/atoms/toggle/toggle.types.ts, src/constants/constants.ts, src/core/endpoints/index.ts, src/core/endpoints/index.types.ts, src/core/routes/routes.tsx, src/core/types.ts, src/pages/notifications/mobile/mobile.tsx, src/pages/notifications/settings/mobile/mobile.module.scss, src/pages/notifications/settings/mobile/mobile.tsx, src/pages/notifications/settings/settings.service.ts, src/pages/notifications/settings/settings.tsx, src/pages/notifications/settings/settings.types.ts
=> Feat/ENG 881/notification settings

src/core/routes/routes.tsx, src/pages/notifications/desktop/desktop.module.scss, src/pages/notifications/desktop/desktop.tsx, src/pages/notifications/settings/desktop/desktop.module.scss, src/pages/notifications/settings/desktop/desktop.tsx, src/pages/notifications/settings/settings.container.tsx, src/pages/notifications/settings/settings.shared.tsx
=> Feat/ENG-881/Web Notification Settings

package-lock.json, package.json, src/core/http.ts, src/core/socket.ts, src/pages/chat/message-detail/mobile/mobile.tsx
it's simple a way to realtime chat
=> realtime chat

src/components/organisms/notification-list/notification-list.module.scss, src/core/routes/routes.tsx, src/pages/notifications/desktop/desktop.module.scss, src/pages/notifications/desktop/desktop.tsx, src/pages/notifications/desktop/desktop.types.ts, src/pages/notifications/mobile/mobile.service.ts, src/pages/notifications/mobile/mobile.tsx, src/pages/notifications/mobile/mobile.types.ts, src/pages/notifications/notifications.container.tsx, src/pages/notifications/notifications.service.ts, src/pages/notifications/notifications.shared.tsx, src/pages/notifications/notifications.types.ts
=> Feat/Web Notifications

src/components/organisms/alert-modal/alert-modal.module.scss, src/components/templates/withdraw-missions/index.tsx, src/components/templates/withdraw-missions/withdraw-missions.module.scss, src/components/templates/withdraw-missions/withdraw-missions.types.ts, src/core/types.ts, src/pages/job-offer-reject/offer/offer.services.ts, src/pages/job-offer-reject/offer/offer.tsx, src/pages/payment/credit-card/mobile/mobile.module.scss, src/pages/payment/credit-card/mobile/mobile.service.ts, src/pages/payment/credit-card/mobile/mobile.tsx, src/pages/payment/mobile/mobile.tsx, src/pages/sidebar/mobile/mobile.tsx, src/pages/wallet/mobile/mobile.tsx, src/pages/wallet/wallet.service.ts, src/pages/wallet/wallet.types.ts
=> Feat/eng 855/fiat wallet

src/components/templates/web-modal/index.tsx, src/components/templates/web-modal/web-modal.types.ts, src/pages/complete-mission/desktop/desktop.tsx, src/pages/job-create/info/info-modal/index.tsx, src/pages/job-create/info/info-modal/info-modal.types.ts, src/pages/job-create/info/mobile/mobile.tsx, src/pages/job-create/my-jobs/desktop/desktop.tsx, src/pages/job-create/skills/skills-modal/index.tsx, src/pages/job-create/skills/skills-modal/skills-modal.types.ts, src/pages/job-create/social-causes/social-causes-modal/index.tsx, src/pages/job-create/social-causes/social-causes-modal/social-causes-modal.types.ts, src/pages/offer-received/desktop/desktop.tsx
=> Fix/eng 995/job fixes

src/components/molecules/notification-item/notification-item.module.scss, src/components/organisms/notification-list/notification-list.tsx, src/components/organisms/notification-list/notification-list.types.ts, src/pages/notifications/desktop/desktop.tsx, src/pages/notifications/mobile/mobile.tsx, src/pages/notifications/notifications.types.ts
=> Fix/ENG-982/Notification Items

src/components/templates/withdraw-missions/index.tsx, src/components/templates/withdraw-missions/withdraw-missions.types.ts, src/pages/wallet/desktop/desktop.tsx, src/pages/wallet/mobile/mobile.tsx, src/pages/wallet/wallet.service.ts
=> feat/ENG-173/Payment History Crypto

src/components/organisms/job-list/job-list.tsx, src/pages/jobs/jobs.jobStructuredData.ts
1. A function (jobs.jobStructuredData.ts) is added to create JSON LD structured data of jobs
2. The structured data is injected to the jobs page 3- The result is tested by google rich result: see the result [here](https://search.google.com/test/rich-results/result?id=w7aLB4ajRceem1v5eOOuFQ).
1. Deployment
2. Update sitemap.xml or use Indexing API to inform google about changes
=> Indexing jobs by google jobs

src/dapp/dapp.config.ts, src/dapp/dapp.connect.tsx, src/dapp/dapp.service.ts, src/dapp/wallets/flint.ts, src/global.d.ts, src/pages/payment/payment.shared.tsx, src/vite-env.d.ts
=> flint wallet

public/robots.txt, public/sitemap.xml
Two files are added: sitemap.xml and robots.txt
These files make google to crawl our site and index the jobs
=> sitemap.xml file is added

src/stories/iconDropDown.stories.tsx
Just attempting to merge IconDropDown fixes done by Marjan to main.
=> merge iconDropDown fixes to main

.eslintrc.json, package-lock.json, package.json
1. Updated ESLint.
2. Updated the .eslint.json file to include the typescript linter classes
=> Added eslint-ts support

src/Nowruz/modules/general/components/SearchDropdown/index.tsx, src/Nowruz/modules/general/components/multiSelect/chip.tsx, src/Nowruz/modules/general/components/multiSelect/multiSelect.module.scss, src/Nowruz/modules/general/components/multiSelect/multiSelect.tsx, src/components/_primitives.scss
In multi select component (select skills/social causes) 
* user can focus on selected items by Tab and remove them by enter
* user can focus chips from the list and select them by enter
=> focus on chips by tab and select them by enter

src/Nowruz/pages/sign-up/Onboarding/index.tsx
It is a fix related to this ticket:
https://www.notion.so/socious/8a30813ce9ab4e39bc75fcd12f37aee3?v=01b034174697411cb1930efa9f7d6dc4&p=6c6d54644d3d4c65baf831919483a789&pm=s
=> change 'org' avatar in onboarding to 'user' avatar

node_modules/.package-lock.json, package-lock.json, package.json, src/core/api/http.ts, src/dapp/dapp.config.ts, src/dapp/dapp.connect.tsx, src/dapp/dapp.service.ts, src/dapp/dapp.types.ts, src/dapp/wallets/flint.ts, src/pages/job-offer-reject/offer/mobile/mobile.tsx, src/pages/job-offer-reject/offer/offer-modal/index.tsx, src/pages/job-offer-reject/offer/offer.shared.tsx, src/pages/job-offer-reject/overview/components/hired/hired.tsx, src/pages/job-offer-reject/overview/desktop/desktop.tsx, src/pages/offer-received/desktop/desktop.tsx, src/pages/offer-received/offer-received.shared.tsx, src/pages/payment/payment.shared.tsx
https://www.notion.so/socious/Bug-wagmi-configuration-on-DEV-d6e851dce2cb4aca869c014a0074dd92?pvs=23
=> dapp upgrade

src/Nowruz/modules/Auth/containers/onboarding/City/useCity.tsx, src/Nowruz/modules/Auth/containers/onboarding/ImageBio/useImageBio.tsx, src/Nowruz/modules/Auth/containers/onboarding/OrganizationContact/index.tsx, src/Nowruz/modules/Auth/containers/onboarding/OrganizationContact/useOrganizationContact.tsx, src/Nowruz/modules/Auth/contexts/onboarding/sign-up-user-onboarding.context.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/Nowruz/modules/userProfile/containers/editInfo/useEditInfo.tsx, src/core/api/geo/geo.types.ts
Added timezone to city search component in this parts: 
* user signup
* org signup
* user/org profile edit
https://www.notion.so/socious/W1-2-4dc13e786d2b4c55ae499113971764cf?p=b120b6c50d8e4ae7991b396859b9e444&pm=s
=> add timezone to city (onboarding, profile, edit info)

src/Nowruz/modules/general/components/Accordion/Accordion.types.ts, src/Nowruz/modules/general/components/Accordion/accordion.module.scss, src/Nowruz/modules/general/components/Accordion/index.tsx, src/Nowruz/modules/general/components/Accordion/reducer.ts
Created a component accordion
Media:
https://github.com/socious-io/web-app-v2/assets/5590282/25b30266-7776-47bd-a1ce-489bbc5da0c7
=> component: accordion

src/Nowruz/pages/oauth/google.tsx
**Ticket:** [Apply to the job position with a new Google account](https://www.notion.so/socious/Apply-to-the-job-position-with-a-new-Google-account-17b72672f8b444d68ad1235aae78fd42?pvs=4)
**Description:**
- Redirect it to the job if the entry point is Apply Job (we don't need to redirect to user particulars because it is already collected, we can redirect it but we were not able to proceed unless we change the username)
- Redirect to Onboarding if the entry point is Sign in google.
**Media:**
[Google sign up.pdf](https://github.com/socious-io/web-app-v2/files/13887551/Google.sign.up.pdf)
https://github.com/socious-io/web-app-v2/assets/5590282/de91d39e-933c-4930-b60a-ac363f104311
=> chore: fix google sign in

node_modules/.package-lock.json, package-lock.json, src/Nowruz/modules/Jobs/components/JobListingCard/index.tsx, src/Nowruz/modules/Jobs/modules/JobListing/index.tsx, src/Nowruz/modules/Jobs/modules/JobListing/useJobListing.tsx, src/Nowruz/modules/general/components/Chip/Chip.types.ts, src/Nowruz/modules/general/components/Chip/chip.module.scss, src/Nowruz/modules/general/components/Chip/index.tsx, src/Nowruz/modules/general/components/Pagination/Pagination.types.ts, src/Nowruz/pages/jobs/List/index.tsx, src/core/router/router.blueprint.tsx
This PR has solved the issues reported on this ticket:
https://www.notion.so/socious/U-job-listings-all-job-2b119c77feb14ac28629c0c861ddff2e
=> fix reported bugs on job listing

cypress.env.tpl, cypress/e2e/authentication/sign-in.cy.ts, cypress/e2e/authentication/sign-up.cy.ts, tsconfig.json
- changed static email to randomly generated email for sign up test. 
- small fixes.
=> configured cypress files

src/Nowruz/modules/Auth/containers/signup/UserDetails/index.tsx, src/Nowruz/modules/Auth/containers/signup/UserDetails/useUserDetails.tsx, src/Nowruz/pages/oauth/google.tsx, src/core/api/auth/auth.types.ts
This will prefill the user information once they use Google sign up and redirect to complete the sign up. screen will ask for last name, first name and username
=> Fix: google to force redirect to signup, prefill the username details

src/Nowruz/modules/Auth/containers/signup/UserDetails/useUserDetails.tsx, src/core/router/router.blueprint.tsx
Switch to use loader data in sign-up complete screen
=> fix: useLoader to fetch data

src/Nowruz/modules/Auth/containers/onboarding/OrganizationContact/index.tsx, src/Nowruz/modules/Auth/containers/onboarding/OrganizationContact/useOrganizationContact.tsx, src/Nowruz/modules/general/components/countryFlag/countryFlag.module.scss, src/Nowruz/modules/userProfile/components/about/about.module.scss, src/Nowruz/modules/userProfile/components/mainInfo/index.tsx, src/Nowruz/modules/userProfile/components/profileHeader/desktopHeader.tsx, src/Nowruz/modules/userProfile/components/profileHeader/profileHeader.module.scss, src/Nowruz/modules/userProfile/components/website/index.tsx, src/constants/ORGANIZATION_SIZE.ts, src/stories/search-dorpdown.stories.tsx
**Ticket:** [Bugs related to: OP. My profile: about tab (excluding all other tabs)](https://www.notion.so/socious/Bugs-related-to-OP-My-profile-about-tab-excluding-all-other-tabs-712b115117c04ba585626d26440e5403?pvs=4)
**Definition of done:**
**Media:**
https://github.com/socious-io/web-app-v2/assets/5590282/da62f96d-b2fe-4eb9-82ee-e164f59399af
=> fix: design discrepancies and feedback for OP. My profile

src/Nowruz/modules/general/components/profileCard/index.tsx, src/Nowruz/modules/userProfile/components/mainInfo/index.tsx, src/Nowruz/modules/userProfile/components/website/index.tsx
Description:
Fix the country flag rendering error if the country is null
=> chore: fix country if country is null

src/Nowruz/modules/general/components/input/input.module.scss, src/Nowruz/modules/userProfile/containers/editSummery/index.tsx, src/Nowruz/modules/userProfile/containers/editSummery/useEditSummary.tsx
This PR has fixed the issues reported on this ticket:
https://www.notion.so/socious/OP-edit-profile-edit-summary-8773abb475d440d
=> fixed edit summary scroll and length validation

src/Nowruz/modules/general/components/Tooltip/Tooltip.types.ts, src/Nowruz/modules/general/components/Tooltip/index.tsx
This component will be for the tooltip component utilizing the Material UI Tooltip
Media:
=> tooltip-component

node_modules/.package-lock.json, package-lock.json, package.json, src/Nowruz/modules/Jobs/components/OrganizationJobCard/index.tsx, src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx, src/Nowruz/modules/Jobs/containers/OrgOfferModal/OrgOfferModal.types.ts, src/Nowruz/modules/Jobs/containers/OrgOfferModal/index.tsx, src/Nowruz/modules/Jobs/containers/OrgOfferModal/org-offer-modal.module.scss, src/Nowruz/modules/Jobs/containers/OrgOfferModal/useOrgOffer.tsx, src/Nowruz/modules/Jobs/modules/JobListing/useJobListing.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/useOrganizationJobListing.tsx, src/Nowruz/modules/general/components/AlertModal/AlertModal.types.ts, src/Nowruz/modules/general/components/AlertModal/index.tsx, src/Nowruz/modules/general/components/ButtonGroups/buttonGroups.module.scss, src/Nowruz/modules/general/components/EmptyState/index.tsx, src/Nowruz/modules/general/components/input/InputDropdown/index.tsx, src/Nowruz/modules/general/components/input/input.tsx, src/Nowruz/modules/general/components/input/input.types.ts, src/Nowruz/pages/jobs/List/index.tsx, src/Nowruz/pages/jobs/List/list.module.scss, src/Nowruz/pages/jobs/detail/applicants/applicant.tsx, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/applicants/table.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicant.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx, src/Nowruz/pages/jobs/detail/index.tsx, src/Nowruz/pages/jobs/detail/useJobDetailTabs.tsx, src/core/router/router.blueprint.tsx
For this PR I just reused the same path which is `jobs/listing` content will change based on identity. Either `JobListing` or `OrganizationJobListing`
https://github.com/socious-io/web-app-v2/assets/5590282/d325fa9d-7ee9-4804-9b37-c1158268e31c
=> OP: Check Applicants + Org Offer

src/Nowruz/modules/general/components/avatarProfile/avatarProfile.module.scss, src/Nowruz/modules/general/components/iconButton/iconButton.module.scss, src/Nowruz/modules/general/components/multiSelect/multiSelect.module.scss, src/Nowruz/modules/general/components/slideoutMenu/sildeoutMenu.module.scss, src/Nowruz/modules/userProfile/components/profileHeader/profileHeader.module.scss, src/components/_primitives.scss, src/components/_reset.scss
- Updated version of new reset
- Added default font in body declaration (mistakenly done in ::after)
- Updated colors and radius
- Added spacing, widths, containers, font-size variables
- Corrected name for shadows and focus rings, also instances in files using it
=> Update variables in primitives and reset files

node_modules/.package-lock.json, src/Nowruz/modules/Jobs/jobCreate/components/Header/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/contract/components/PaymentCrypto/index.tsx, src/Nowruz/modules/contract/components/PaymentCrypto/paymentCrypto.types.ts, src/Nowruz/modules/contract/components/PaymentCrypto/usePaymentCrypto.tsx, src/Nowruz/modules/contract/components/contractDetailTab/index.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/index.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx, src/Nowruz/modules/contract/components/paymentFiat/index.tsx, src/Nowruz/modules/contract/components/paymentFiat/paymentFiat.types.ts, src/Nowruz/modules/contract/components/paymentFiat/usePaymentFiat.tsx, src/Nowruz/modules/contract/components/paymentSummary/index.tsx, src/Nowruz/modules/contract/components/paymentSummary/paymentSummary.module.scss, src/Nowruz/modules/general/components/AlertModal/alert-modal.module.scss, src/components/_reset.scss, src/core/api/jobs/jobs.types.ts, src/dapp/dapp.connect.tsx
- fixed the issues mentioned in this ticket
https://www.notion.so/socious/OP-Proceed-to-the-payment-page-Fiat-53f50b76fc604d41af23782777dde83f
=> TAS-956/fix fiat payment

src/Nowruz/modules/Jobs/components/JobListingCard/index.tsx, src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx, src/Nowruz/modules/Jobs/components/jobDetailDescription/index.tsx, src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/Jobs/jobCreate/components/createScreenQuestion/createScreenQuestion.types.ts, src/Nowruz/modules/Jobs/jobCreate/components/createScreenQuestion/createScreenQuestions.module.scss, src/Nowruz/modules/Jobs/jobCreate/components/createScreenQuestion/index.tsx, src/Nowruz/modules/Jobs/jobCreate/components/createScreenQuestion/useCreateScreenQuestion.tsx, src/Nowruz/modules/Jobs/jobCreate/components/screenQuestion/index.tsx, src/Nowruz/modules/Jobs/jobCreate/components/screenQuestion/screenQuestions.module.scss, src/Nowruz/modules/Jobs/jobCreate/components/screenQuestion/screenQuestions.type.ts, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/useJobCreateForm.tsx, src/Nowruz/modules/contract/components/contractCard/useContractCard.tsx, src/Nowruz/modules/general/components/Button/button.module.scss, src/Nowruz/modules/general/components/RadioGroup/index.tsx, src/core/api/http.ts
for some jobs such as 'product manager' created by 'Bridge for Peace', the detail page was broken, because there were not any mission or bio for the company. The bug is fixed in this PR to display nothing if the mentioned fields are not available instead of a failure
=> TAS-995: Fix/job detail error

src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/useJobCreateForm.tsx, src/Nowruz/modules/contract/components/contractCard/useContractCard.tsx, src/Nowruz/modules/general/components/RadioGroup/index.tsx, src/core/api/http.ts
Related ticket:
https://www.notion.so/socious/Issues-related-to-the-Nowruz-Job-preview-and-Create-job-Disable-Preview-4ffaf9c493db4b9d8796122af3ef84f6
=> TAS_828/fix create job

src/Nowruz/modules/Jobs/containers/OrgOfferModal/index.tsx, src/Nowruz/modules/Jobs/containers/OrgOfferModal/org-offer-modal.module.scss, src/Nowruz/modules/Jobs/containers/OrgOfferModal/useOrgOffer.tsx, src/Nowruz/modules/general/components/input/input.tsx, src/components/_reset.scss
Fix the following task define on the ticket
=> TAS-591: OP Offers fix

src/Nowruz/pages/sign-up/Email/index.tsx
=> TAS-969: Add google button on sign-up

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx
Ticket address:
https://www.notion.so/socious/Remove-mission-from-the-top-of-the-Job-details-page-7eb24fa785074181beedf1d456a51f13
=> TAS-1061/remove mission from job detail header

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx
Ticket address:
https://www.notion.so/socious/Bug-Social-cause-and-skill-tags-should-be-fully-spelled-out-240ac6d1b99d43518382b80f22a0ae3e
=> TAS-1062/fixed skills and causes tags in job detail page

src/Nowruz/modules/Jobs/components/OrganizationJobCard/index.tsx, src/Nowruz/modules/Jobs/components/OrganizationJobCard/organization-job-card.module.scss, src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/Nowruz/modules/general/components/ButtonGroups/buttonGroups.module.scss, src/Nowruz/modules/general/components/ButtonGroups/index.tsx, src/Nowruz/pages/jobs/List/index.tsx, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/index.tsx, src/Nowruz/pages/jobs/detail/useJobDetailTabs.tsx
This will fix mobile view of OP: Job Overview
=> TAS-990: Organization job details

src/Nowruz/modules/contract/components/addCardModalUser/addCardModalUser.types.ts, src/Nowruz/modules/contract/components/addCardModalUser/index.tsx, src/Nowruz/modules/contract/components/addCardModalUser/useAddCardModalUser.tsx, src/Nowruz/modules/contract/components/contractCard/index.tsx, src/Nowruz/modules/contract/components/contractCard/useContractCard.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/index.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx, src/Nowruz/modules/contract/components/selectBankAccountUser/index.tsx, src/Nowruz/modules/contract/components/selectBankAccountUser/selectBankAccountUser.types.ts, src/Nowruz/modules/contract/components/walletModal/index.tsx, src/Nowruz/modules/contract/components/walletModal/walletModal.types.ts, src/Nowruz/modules/general/components/alertMessage/alertMessage.types.ts, src/Nowruz/modules/general/components/alertMessage/index.tsx, src/Nowruz/modules/general/components/featuredIcon-new/FeaturedIcon.types.ts, src/Nowruz/modules/general/components/featuredIcon-new/featued-icon.module.scss, src/Nowruz/modules/general/components/featuredIcon-new/index.tsx, src/Nowruz/modules/general/components/modal/index.tsx, src/Nowruz/modules/general/components/modal/modal.types.ts, src/core/api/auth/auth.types.ts, src/core/utils.tsx
related ticket:
https://www.notion.so/socious/U-Accept-offer-Crypto-and-Fiat-Umaya-can-t-accept-offer-unless-Umaya-has-wallet-or-bank-account-405354c791774473b16a1569fc8dfab7
=> TAS-1010: U.Accept offer (Crypto and Fiat)

src/Nowruz/modules/Jobs/components/OrganizationJobCard/index.tsx, src/Nowruz/modules/general/components/horizontalTabs/index.tsx, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/applicants/table.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx, src/Nowruz/pages/jobs/detail/index.tsx, src/Nowruz/pages/jobs/detail/useJobDetailTabs.tsx
This will
- Add new tab Rejected
- Update the table on reject applicant
=> TAS-992/OP:Applicants-tab

src/Nowruz/pages/sign-up/Email/index.tsx
The button component behaves weirdly on adding a style class
=> chore: fix google button styling not with class

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/Jobs/containers/OrgOfferModal/index.tsx, src/Nowruz/modules/Jobs/containers/OrgOfferModal/useOrgOffer.tsx, src/Nowruz/modules/general/components/input/input.tsx, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/applicants/table.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx, src/Nowruz/pages/jobs/detail/index.tsx, src/index.scss
This will fix making offer Crypto decimal value.
=> TAS-591/Offer-Crypto-decimal

src/Nowruz/modules/Jobs/jobCreate/components/createScreenQuestion/index.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx, src/Nowruz/modules/contract/components/walletModal/index.tsx, src/Nowruz/modules/general/components/alertMessage/alertMessage.module.scss, src/Nowruz/modules/general/components/alertMessage/index.tsx, src/Nowruz/modules/general/components/featuredIconOutlined/featuredIconOutlined.module.scss
Resolved these issues in accepting offer
1) typo issue: To accept this offer your… → To accept this offer you…
2) The icon for connecting the wallet is different from Figma.
3)The icon you used on the screen related to “bank account required” should be on top based on Figma (currently, is in the middle), also it shouldn’t be like a tick symbol, it should be like a ! symbol.
4) For volunteer offer, we shouldn’t ask user to add it’s card.
=> TAS-1010/fixed accept offer issues

src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx
=> TAS-959/OP Confirm completion

src/Nowruz/modules/contract/components/PaymentCrypto/usePaymentCrypto.tsx, src/Nowruz/modules/contract/components/contractCard/contractCard.types.ts, src/Nowruz/modules/contract/components/contractCard/index.tsx, src/Nowruz/modules/contract/components/contractCard/useContractCard.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/contractDetailsSlider.types.ts, src/Nowruz/modules/contract/components/contractDetailsSlider/index.tsx, src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx, src/Nowruz/modules/contract/components/paymentFiat/usePaymentFiat.tsx, src/Nowruz/pages/contracts/index.tsx, src/Nowruz/pages/contracts/useContracts.tsx, src/core/router/router.blueprint.tsx, src/store/index.ts, src/store/reducers/contracts.reducer.ts, src/store/thunks/contracts.thunk.ts
Changed the logic, used redux to manage contracts. 
After each action by user (e.g. accepting offer) , contracts in redux store is immediately updated and update in backend API is done asynchronously
=> TAS-1044/update sontract status immediately in the list after any actions by user

src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/Nowruz/modules/general/components/horizontalTabs/horizontalTabs.module.scss, src/Nowruz/modules/general/components/horizontalTabs/horizontalTabs.types.ts, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx, src/Nowruz/pages/jobs/detail/useJobDetailTabs.tsx
Created the offered tab  on Organization created job details
=> TAS-992/organization offered tab

src/Nowruz/modules/general/components/slideoutMenu/sildeoutMenu.module.scss, src/Nowruz/modules/layout/components/headerNavBar/index.tsx, src/Nowruz/modules/layout/containers/notifications/index.tsx, src/Nowruz/modules/layout/containers/notifications/useNotifications.tsx
Convert the notification slider into new slider component
=> Tas 912/notification slide

src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/core/router/router.blueprint.tsx
Fix when accessing the /created jobs for OP
=> fix error when accessing /jobs/created on nowruz

src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/Nowruz/pages/jobs/detail/index.tsx, src/core/router/router.blueprint.tsx
Remove unnecessary message for OP in job details
=> TAS-1165/op applied for this job

src/Nowruz/modules/Search/components/FilterSlider/useFilterSlider.tsx, src/Nowruz/modules/Search/components/ResultList/index.tsx, src/Nowruz/modules/Search/components/ResultList/result-list.module.scss, src/Nowruz/modules/Search/components/SearchInput/SearchInput.types.ts, src/Nowruz/modules/Search/components/SearchInput/index.tsx, src/Nowruz/modules/Search/containers/SearchModal/index.tsx, src/Nowruz/modules/general/components/avatarLabelGroup/avatarLabelGroup.types.ts, src/Nowruz/modules/general/components/avatarLabelGroup/index.tsx, src/Nowruz/modules/general/components/profileCard/index.tsx, src/Nowruz/pages/search/useSearch.tsx
1. Hover the whole width on Search Modal
2. User click the search bar, it opens the modal and autofocus directly on the search input in Modal
3. User should be able to close the modal with ESC key
4. Profile Card Social causes are CAPITALIZED
5. Cannot click on a profile OP/User search results
6. Retain Location after filter apply
=> TAS-1026: fix all reported issues

src/Nowruz/modules/userProfile/components/mainInfo/index.tsx
Check profile type and conditional rendering of Impact point and languages
=> TAS-1164/check-profile-type

src/Nowruz/modules/userProfile/components/impact/index.tsx, src/Nowruz/modules/userProfile/containers/impact/Overview.tsx, src/Nowruz/pages/impact/impact.module.scss, src/Nowruz/pages/impact/index.tsx, src/Nowruz/pages/impact/useImpact.tsx, src/core/api/users/users.types.ts, src/core/router/router.blueprint.tsx
My impact points overview
URL: /nowruz/profile/users/${username}/impact
=> TAS-1090/my impact overview tab

src/Nowruz/modules/Search/components/FilterSlider/useFilterSlider.tsx, src/Nowruz/modules/userProfile/components/impact/index.tsx, src/Nowruz/pages/impact/useImpact.tsx, src/Nowruz/pages/search/index.tsx, src/Nowruz/pages/search/useSearch.tsx, src/Nowruz/pages/userProfile/useUserProfile.tsx
1. Hide Reviews and Services in U: Profile
2. Don't show Decimals in Impact points
3. Compute Volunteered hours
4. Show country if filter has been applied
=> TAS-1189: designers feedback

src/Nowruz/modules/general/components/horizontalTabs/horizontalTabs.types.ts, src/Nowruz/modules/general/components/horizontalTabs/index.tsx, src/Nowruz/modules/userProfile/components/jobs/index.tsx, src/Nowruz/modules/userProfile/components/jobs/organization-jobs.module.scss, src/Nowruz/modules/userProfile/components/jobs/useOrganizationJobs.tsx, src/Nowruz/pages/orgProfile/index.tsx, src/Nowruz/pages/orgProfile/useOrgProfile.tsx, src/core/router/router.blueprint.tsx
Created the jobs tab on Org Profile
=> TAS-1218/socious career page

src/Nowruz/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx
=> TAS-1220: Hide Contest button

src/Nowruz/modules/general/components/link/index.tsx, src/Nowruz/modules/general/components/link/link.types.ts, src/Nowruz/modules/userProfile/components/website/index.tsx
=> TAS-1225: External link open new tab

src/Nowruz/modules/contract/components/contractCard/index.tsx, src/Nowruz/modules/contract/components/contractCard/useContractCard.tsx
Not showing correct currency on Contract Card
=> TAS-1224: Crypto offers

src/Nowruz/modules/layout/components/footer/footer.tsx, src/Nowruz/modules/layout/components/headerNavBar/index.tsx, src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx, src/Nowruz/pages/setting/index.tsx
Hiding Settings menu on Org
Hiding Credentials
=> TAS-1209: Hide settings and credentials

src/Nowruz/modules/Jobs/modules/JobListing/useJobListing.tsx, src/core/router/router.blueprint.tsx
Increase number of displayed jobs
=> TAS-1275: Increase displayed jobs

src/Nowruz/modules/Jobs/components/OrganizationJobCard/index.tsx, src/Nowruz/modules/Jobs/components/OrganizationJobCard/organization-job-card.module.scss, src/Nowruz/modules/Jobs/jobCreate/components/Header/Header.types.ts, src/Nowruz/modules/Jobs/jobCreate/components/Header/index.tsx, src/Nowruz/modules/Jobs/jobCreate/components/JobPreviewModal/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/useJobCreateForm.tsx, src/Nowruz/modules/general/components/RadioGroup/index.tsx, src/Nowruz/pages/jobs/Edit/index.tsx, src/core/router/router.blueprint.tsx
This the the Edit Job operation
=> TAS-1028/op edit job

src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx
=> TAS-1326-copy-change-how-many-hours-are-expected

src/Nowruz/modules/layout/containers/notifications/useNotifications.tsx
=> TAS-1290: Notifications redirect

src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx
URL in copy job URL is showing capacitor as domain.
=> TAS-1310: iOS + Android issue on URL of job in job details (TestFlight)

src/Nowruz/modules/general/components/RadioGroup/index.tsx
**Issue** on when we don't have selectedItem from outside.
=> TAS-1407/Fix-RadioGroups

src/Nowruz/modules/general/components/stepperCard/index.tsx, src/Nowruz/modules/general/components/stepperCard/stepperCard.types.tsx, src/Nowruz/modules/layout/containers/notifications/index.tsx, src/Nowruz/modules/layout/containers/notifications/useNotifications.tsx, src/Nowruz/modules/userProfile/components/about/experience/experience.tsx, src/Nowruz/modules/userProfile/components/about/experience/useExperience.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/index.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/index.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx, src/core/api/credentials/credentials.api.ts, src/core/api/users/users.types.ts
**This branch is related to receiving Umaya's request notification to verify the experience.**
FE tasks:
TODO:
=> TAS-1427/Umaya-Request-Notif

src/Nowruz/modules/general/components/stepperCard/index.tsx, src/Nowruz/modules/general/components/stepperCard/stepperCard.types.tsx, src/Nowruz/modules/userProfile/components/about/experience/experience.tsx, src/Nowruz/modules/userProfile/components/about/experience/useExperience.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/index.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/index.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx, src/core/api/credentials/credentials.api.ts, src/core/api/users/users.types.ts
**This branch is mainly related to verifying experience**, including:
Also, there are some bugs, including:
TODO:
=> TAS-1111/Verify-User-Experience

src/Nowruz/modules/general/components/stepperCard/index.tsx, src/Nowruz/modules/general/components/stepperCard/stepperCard.types.tsx, src/Nowruz/modules/userProfile/components/about/experience/experience.tsx, src/Nowruz/modules/userProfile/components/about/experience/useExperience.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/index.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/index.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx, src/core/api/credentials/credentials.api.ts, src/core/api/users/users.types.ts
**This branch is related to editing only the description and deleting experience after `verified` status**.
TODO:
=> TAS-1112/Readonly-After-Verification

src/Nowruz/modules/credentials/credentialDetails/index.tsx, src/Nowruz/modules/credentials/credentialDetails/useCredentialDetails.tsx, src/Nowruz/modules/credentials/credentialsList/index.tsx, src/Nowruz/modules/credentials/credentialsList/useCredentialsList.tsx, src/Nowruz/modules/credentials/issuedList/index.tsx, src/Nowruz/modules/credentials/issuedList/issuedList.module.scss, src/Nowruz/modules/credentials/issuedList/useIssuedList.tsx, src/Nowruz/modules/general/components/RadioGroup/index.tsx, src/Nowruz/modules/layout/containers/notifications/useNotifications.tsx, src/Nowruz/modules/userProfile/components/about/experience/useExperience.tsx, src/Nowruz/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/index.tsx, src/Nowruz/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx, src/Nowruz/pages/Credentials/index.tsx, src/Nowruz/pages/Credentials/useCredentials.tsx, src/core/api/credentials/credentials.types.ts, src/core/api/users/users.types.ts
**This branch is related to approval notif**, including:
- **for user**: 
- All `APPROVED` and `CLAIMED` experiences
- **for org**:
- out of the scope of this ticket
- **for user**:
- All `PENDING` and `REJECTED` experiences
- **for org**:
- Except `ISSUED` experiences
TODO:
=> TAS-1433/Approval-Notif

src/Nowruz/modules/layout/components/linksContainer/linksContainer.tsx, src/Nowruz/modules/layout/components/linksContainer/linksContainer.types.ts, src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx
**FIX:**
- `create an organization`/`create a talent` link issue on mobile mode
=> TAS-1337/Create-Org-Talent-Link

src/Nowruz/modules/Auth/containers/forgetPassword/EmailForm/useEmailForm.tsx, src/Nowruz/modules/Auth/containers/onboarding/OrganizationContact/useOrganizationContact.tsx, src/Nowruz/modules/Auth/containers/signin/SignInForm/useSignInForm.tsx, src/Nowruz/modules/Auth/containers/signup/EmailForm/useEmailForm.tsx, src/Nowruz/modules/authGuard/containers/signin/useSignInForm.tsx, src/Nowruz/modules/authGuard/containers/signup/useSignupForm.tsx, src/core/api/auth/auth.types.ts
**FIX:**
- Validation for a wide range of emails such as our bug: (sam.lambert@zengate.global)
Invalid Email Addresses:
- missing top-level domain
- multiple '@' symbols
- special character '!' not allowed
=> TAS-1509/Email-Validation

src/Nowruz/modules/general/components/avatar/avatar.module.scss
**FIX:**
- prevent to stretch and enlarging the avatars
=> TAS-1308/Prevent-Fill-Avatar

src/Nowruz/modules/settings/components/password/index.tsx, src/Nowruz/modules/settings/components/password/usePassword.tsx
**This branch is related to fixing some issues in `settings/password`**, including:
=> TAS-1240/Current-Pass-Alert

src/Nowruz/modules/layout/components/linkItem/linkItem.module.scss
**FIX:**
- broken style in tablet size
=> TAS-1093/Tablet-Style-Nav

src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/general/components/input/input.module.scss, src/Nowruz/modules/general/components/input/input.tsx, src/Nowruz/modules/general/components/input/input.types.ts, src/Nowruz/pages/jobs/detail/index.tsx
=> TAS-1006/Styling-Issues

src/Nowruz/modules/general/components/profileCard/index.tsx, src/Nowruz/modules/userProfile/components/mainInfo/index.tsx, src/Nowruz/pages/connections/index.tsx, src/Nowruz/pages/connections/useConnections.tsx, src/Nowruz/pages/dashboard/index.tsx, src/Nowruz/pages/dashboard/useDashborad.tsx, src/core/api/organizations/organizations.types.ts, src/core/api/users/users.types.ts, src/core/router/router.blueprint.tsx
you can find here a recording of changes:
https://drive.google.com/file/d/18KuzSJrLRXpwSIslrCCt1BCE63osci9I/view?usp=drive_link
=> fixed connection numbers and links in profile and dashboard

src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx
**FIX:**
- Removed text from the location in the job create form
=> TAS-1531/Remove-Text-Location

src/Nowruz/modules/Search/components/searchResultProfile/index.tsx, src/Nowruz/pages/search/useSearch.tsx
**FIX:**
- clicking on user/organization result card and navigate to their profile.
=> TAS-1279/Click-Search-Cards

src/Nowruz/modules/settings/components/leaveDeleteMember/index.tsx, src/Nowruz/modules/settings/components/leaveDeleteMember/index.type.ts, src/Nowruz/modules/settings/components/orgTeam/index.tsx, src/Nowruz/modules/settings/components/orgTeam/useOrgTeam.tsx, src/Nowruz/modules/settings/components/userTeam/index.tsx, src/Nowruz/modules/settings/components/userTeam/useUserTeam.tsx, src/Nowruz/modules/settings/components/userTeam/userTeam.module.scss, src/core/api/organizations/organizations.types.ts, src/core/api/site/site.types.ts
This branch includes two parts:
- User side: 
- Org side:
TODO:
=> TAS-1448/Remove-Delete-Member

src/Nowruz/modules/layout/components/linksContainer/linksContainer.tsx, src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx
**FIX:**
- Click on Socious logo and navigate to dashboard page
=> TAS-1547/Logo-Navigation

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/general/components/profileCard/index.tsx, src/Nowruz/pages/jobs/detail/index.tsx
**FIX:**
navigate to organization profile on:
- avatar in job details 
- about the org card
=> TAS-1246/Clickable-Avatar-Job-Details

src/Nowruz/modules/credentials/issuedList/index.tsx, src/core/api/credentials/credentials.types.ts
**FIX:**
- org avatar in issued tab of credential pages
=> TAS-1554/Org-Avatar-Credential

src/Nowruz/modules/userProfile/components/mainInfo/index.tsx, src/Nowruz/modules/userProfile/components/website/index.tsx, src/Nowruz/pages/orgProfile/index.tsx, src/Nowruz/pages/orgProfile/orgProfile.module.scss, src/Nowruz/pages/userProfile/index.tsx, src/Nowruz/pages/userProfile/userProfile.module.scss
**FIX:**
- truncate long url of website in org profile
=> TAS-1207/Long-URL-Profile

src/Nowruz/modules/general/components/multiSelect/multiSelect.module.scss
**FIX:**
- removed fixed height for long text badges in `multiselect` component
=> TAS-1555/Long-Text-Badges

src/Nowruz/modules/Search/components/FilterSlider/index.tsx, src/Nowruz/modules/general/components/SearchDropdown/index.tsx
**FIX:**
- Clear indicator according to our icon library
- Clear indicator replaced with dropdown indicator when has selected value
**TODO**:
=> TAS-1344/Fix-Clear-Location

src/Nowruz/modules/general/components/topBanner/index.tsx, src/Nowruz/modules/userProfile/components/impact/index.tsx, src/Nowruz/pages/dashboard/index.tsx
=> TAS-1556/Responsive-Dashboard

src/Nowruz/modules/general/components/stepperCard/index.tsx, src/Nowruz/modules/general/components/stepperCard/stepperCard.module.scss, src/Nowruz/modules/userProfile/components/about/about.module.scss, src/Nowruz/modules/userProfile/components/about/education/educations.tsx, src/Nowruz/modules/userProfile/components/about/experience/experience.tsx
**FIX:**
- action button inside of each work experience (in `StepperCard`)
- style of disabled action button according to design
- conditions and text issues in experience/education certificate according to design
=> TAS-1552-1553/Action-Button-Stepper

src/Nowruz/modules/credentials/experienceDetails/index.tsx, src/Nowruz/modules/credentials/experienceDetails/useExperienceDetails.tsx, src/core/api/users/users.types.ts
- add `estimated total hours` for `one-off` job like as `estimated weekly hours` for `part-time`
=> TAS-1583/Total-Hours-Experience

src/Nowruz/modules/credentials/credentialsList/useCredentialsList.tsx
**FIX:**
- use the wrong API call for declining education certificates.
@aziinz could you please check and test it on your local?
=> TAS-1661/Fix-Decline-Education

src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx, src/Nowruz/pages/jobs/detail/applicants/cards.tsx, src/Nowruz/pages/jobs/detail/applicants/table.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx, src/Nowruz/pages/jobs/detail/useJobDetailTabs.tsx, src/core/api/site/site.api.ts, src/core/api/site/site.types.ts
=> TAS-999/added search and pagination to applicants(pending,offered,rejected)

capacitor.config.ts, src/Nowruz/modules/Jobs/components/jobDetailAbout/index.tsx
=> TAS-1310/Fix-Capacitor-URL

src/Nowruz/modules/feeds/comments/index.tsx, src/Nowruz/modules/feeds/createPostModal/index.tsx, src/Nowruz/modules/feeds/createPostModal/index.types.ts, src/Nowruz/modules/feeds/createPostModal/useCreatePostModal.tsx, src/Nowruz/modules/feeds/feedItem/index.module.scss, src/Nowruz/modules/feeds/feedItem/index.tsx, src/Nowruz/modules/feeds/feedItem/index.types.ts, src/Nowruz/modules/feeds/feedItem/useFeedItem.tsx, src/Nowruz/modules/feeds/feedsList/index.tsx, src/Nowruz/modules/feeds/feedsList/index.types.ts, src/Nowruz/modules/feeds/removePost/index.tsx, src/Nowruz/modules/feeds/removePost/index.types.ts, src/Nowruz/modules/feeds/replies/index.tsx, src/Nowruz/modules/feeds/reportPost/index.tsx, src/Nowruz/modules/feeds/reportPost/index.types.ts, src/Nowruz/modules/feeds/repostModal/index.tsx, src/Nowruz/modules/feeds/sendBox/index.tsx, src/Nowruz/modules/feeds/threeDotsMenu/index.module.scss, src/Nowruz/modules/feeds/threeDotsMenu/index.tsx, src/Nowruz/modules/feeds/threeDotsMenu/index.types.ts, src/Nowruz/modules/general/components/EmojiPicker/index.tsx, src/Nowruz/modules/general/components/EmojiPicker/index.types.ts, src/Nowruz/modules/general/components/SearchDropdown/index.tsx, src/Nowruz/pages/feeds/index.tsx, src/Nowruz/pages/feeds/useFeeds.tsx, src/core/api/posts/posts.types.ts, src/core/hooks/detectOutside.tsx
**This branch is related to the `TAS-935` and `TAS-924` tickets**, including:
TODO:
=> TAS-935/3dots-Menu

src/Nowruz/modules/contract/components/initiateDisputeModal/index.tsx, src/Nowruz/modules/contract/components/initiateDisputeModal/index.types.ts, src/Nowruz/modules/contract/components/initiateDisputeModal/successInitiateDispute/index.tsx, src/Nowruz/modules/contract/components/initiateDisputeModal/successInitiateDispute/index.types.ts, src/Nowruz/modules/contract/components/initiateDisputeModal/useInitiateDisputeModal.tsx, src/Nowruz/modules/contract/components/sliderAwaiting/index.tsx, src/Nowruz/modules/contract/components/sliderAwaiting/useSliderAwaiting.tsx, src/Nowruz/modules/contract/components/sliderOngoing/index.tsx, src/Nowruz/modules/contract/components/sliderOngoing/useSliderOngoing.tsx, src/Nowruz/modules/general/components/dot/index.tsx, src/Nowruz/modules/general/components/fileUploaderMultiple/fileUploaderMultiple.types.ts, src/Nowruz/modules/general/components/fileUploaderMultiple/index.tsx, src/Nowruz/modules/general/components/fileUploaderMultiple/useFileUploaderMultiple.tsx, src/constants/DISPUTE_CATEGORY.ts, src/core/api/disputes/disputes.api.ts, src/core/api/disputes/disputes.types.ts, src/core/time.ts
**This branch is mainly related to `initiate dispute` modal on the contract page**
BUT including two small changes:
TODO:
=> TAS-1612/Intitate-Dispute

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/general/components/profileCard/index.tsx, src/Nowruz/modules/general/components/profileCard/profileCardHeader.tsx, src/Nowruz/pages/jobs/detail/index.tsx
**FIX: navigate to the organization profile by clicking on:**
=> TAS-1588/Link-Job-Detail

src/Nowruz/modules/general/components/topBanner/index.tsx
=> TAS-1937/Fix-Color-Button

src/Nowruz/pages/dashboard/index.tsx
=> TAS-1765/Dashbaord-Tablet-Issue

src/Nowruz/modules/contract/components/respondDisputeModal/index.tsx, src/Nowruz/modules/contract/components/respondDisputeModal/index.types.ts, src/Nowruz/modules/contract/components/respondDisputeModal/successRespondDispute/index.tsx, src/Nowruz/modules/contract/components/respondDisputeModal/successRespondDispute/index.types.ts, src/Nowruz/modules/contract/components/respondDisputeModal/useRespondDisputeModal.tsx, src/Nowruz/pages/disputes/disputeDetail/index.tsx, src/Nowruz/pages/disputes/disputeDetail/useDisputeDetail.tsx, src/core/api/disputes/disputes.api.ts, src/core/api/disputes/disputes.types.ts
**This branch is mainly related to `respond dispute` in the dispute detail page.**
TODO:
=> TAS-1626/Response-Dispute

src/Nowruz/modules/refer/KYC/index.tsx, src/Nowruz/modules/userProfile/components/about/claimCertificateModal/index.tsx
=> TAS-1873/KYC-QR-Code

src/Nowruz/modules/general/components/avatarProfile/avatarProfile.module.scss, src/Nowruz/modules/general/components/avatarProfile/index.tsx
=> TAS-1755/profile-card-icon

src/Nowruz/modules/refer/referUtils.tsx, src/Nowruz/modules/userProfile/components/about/education/useEducation.tsx
=> TAS-1881/Shorten-QR-Code-URL

src/Nowruz/modules/contract/components/respondDisputeModal/index.tsx, src/Nowruz/modules/contract/components/respondDisputeModal/successRespondDispute/index.tsx, src/Nowruz/modules/contract/components/respondDisputeModal/successRespondDispute/index.types.ts, src/Nowruz/modules/contract/components/respondDisputeModal/useRespondDisputeModal.tsx
**FIX:**
- some texts, including:
=> TAS-1626/Fix-QA-Feedbacks

src/Nowruz/modules/Disputes/ExpiredModal/index.tsx, src/Nowruz/modules/Disputes/ExpiredModal/index.types.ts, src/Nowruz/modules/Disputes/InvitationModal/index.tsx, src/Nowruz/modules/Disputes/InvitationModal/index.types.ts, src/Nowruz/modules/Disputes/InvitationsList/index.tsx, src/Nowruz/modules/Disputes/InvitationsList/index.types.ts, src/Nowruz/modules/Disputes/InvitationsList/useInvitationsList.tsx, src/core/api/disputes/disputes.api.ts
This branch is related to clicking on each row of the invitation list:
TODO:
=> TAS-1854/Accept-Decline-Expire-Modal

capacitor.config.ts, ios/App/App/capacitor.config.json, ios/App/App/public/index.html, src/main.tsx
=> TAS-1785: ios app: The content goes under the navbar

src/Nowruz/modules/Disputes/DisputesList/index.module.scss, src/Nowruz/modules/Disputes/InvitationsList/index.module.scss
=> TAS-2056/Fix-Scroll-Table-Issue

src/Nowruz/modules/layout/components/NotificationItem/index.tsx, src/Nowruz/modules/layout/containers/notifications/index.tsx, src/Nowruz/modules/layout/containers/notifications/useNotifications.tsx, src/core/api/notifications/notifications.types.ts, src/core/hooks/useHideScrollbar.tsx
**This branch is mainly related to dispute flow notifications:**
But also includes:
TODO:
=> TAS-1594/TAS-1596/TAS-1600/Dispute-Notifications

src/Nowruz/modules/Search/components/searchResultProfile/index.tsx, src/Nowruz/modules/general/components/profileCard/index.tsx
=> TAS-2067/Fix-Long-URL

src/Nowruz/modules/general/components/slideoutMenu/sildeoutMenu.module.scss, src/Nowruz/pages/contracts/index.tsx
=> TAS-2066/Fix-Scroll-Background-Contract

src/Nowruz/modules/dispute/components/contributorDashboard/index.tsx, src/Nowruz/modules/dispute/components/contributorDashboard/useContributorDashboard.tsx, src/Nowruz/modules/dispute/components/contributorJoin/index.tsx, src/Nowruz/modules/dispute/components/contributorJoin/useContributorJoin.tsx, src/Nowruz/modules/general/components/AlertModal/alert-modal.module.scss, src/Nowruz/modules/general/components/AlertModal/index.tsx, src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx, src/Nowruz/pages/contribute/index.tsx, src/Nowruz/pages/contribute/useContribute.tsx, src/Nowruz/pages/disputes/disputeDetail/index.tsx, src/Nowruz/pages/disputes/disputeDetail/useDisputeDetail.tsx, src/core/api/site/site.types.ts
=> TAS-2086/TAS-1648/TAS-1597/fix-issues

src/Nowruz/modules/dispute/components/contributorJoin/index.tsx
=> TAS-2113/Fix-Steps-Styles

src/Nowruz/pages/disputes/disputeDetail/index.tsx
=> TAS-2172/Fix-Contract-Info-Styles

src/Nowruz/modules/dispute/components/timelineItem/index.tsx, src/core/stringTransformation.ts
=> TAS-2167/Truncate-Middle-Evidences

src/Nowruz/modules/Disputes/DisputesList/index.tsx, src/Nowruz/modules/Disputes/InvitationsList/index.tsx, src/Nowruz/modules/dispute/components/contributorDashboard/contributorDashboard.module.scss, src/Nowruz/modules/dispute/components/contributorDashboard/index.tsx, src/Nowruz/modules/dispute/components/contributorDashboard/useContributorDashboard.tsx, src/core/relative-time.ts
=> TAS-2166/Fix-Category-Name

src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/feeds/threeDotsMenu/index.module.scss, src/Nowruz/modules/feeds/threeDotsMenu/index.tsx, src/Nowruz/modules/general/components/EmptyState/index.tsx, src/Nowruz/modules/general/components/avatarLabelGroup/index.tsx, src/Nowruz/modules/general/components/threeDotButton/index.tsx, src/Nowruz/modules/general/components/threeDotButton/threeDotButton.module.scss, src/Nowruz/pages/jobs/detail/applicants/table.tsx, src/Nowruz/pages/jobs/detail/applicants/useApplicantAction.tsx
=> TAS-2063/Fix-Styles-Issues-Nowruz

src/Nowruz/modules/layout/index.tsx
=> TAS-1663/Fix-Shifting-Header

src/Nowruz/modules/Jobs/components/JobListingCard/index.tsx, src/Nowruz/modules/Jobs/components/JobListingCard/useJobListingCard.tsx, src/Nowruz/modules/Jobs/components/OrganizationJobCard/index.tsx, src/Nowruz/modules/Jobs/components/jobDetailHeader/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/index.tsx, src/Nowruz/modules/Jobs/jobCreate/containers/JobCreateForm/useJobCreateForm.tsx, src/Nowruz/modules/Jobs/modules/AppliedJobsListing/index.tsx, src/Nowruz/modules/Jobs/modules/AppliedJobsListing/useAppliedJobListing.tsx, src/Nowruz/modules/Jobs/modules/JobListing/index.tsx, src/Nowruz/modules/Jobs/modules/JobListing/useJobListing.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/index.tsx, src/Nowruz/modules/Jobs/modules/OrganizationJobListing/useOrganizationJobListing.tsx, src/Nowruz/modules/Jobs/modules/savedJobListing/index.tsx, src/Nowruz/modules/Jobs/modules/savedJobListing/useSavedJobListing.tsx, src/Nowruz/modules/Search/containers/SearchModal/useSearchModal.tsx, src/Nowruz/modules/layout/components/footer/footer.tsx, src/Nowruz/modules/layout/components/linksContainer/useLinksContainer.tsx, src/Nowruz/pages/jobs/List/index.tsx, src/Nowruz/pages/search/index.tsx, src/Nowruz/pages/search/useSearch.tsx, src/core/router/router.blueprint.tsx
=> TAS-1978/add-pagination-to-URL

src/modules/general/components/modal/index.tsx
**FIX:**
P.S. I prefer to have a separate PR for each ticket (even small issues) because, in the end, PRs are closed, their branches are removed, and all remains are `commits` but other developers can track closed PRs for each ticket. :)
=> TAS-2179/Pointer-Cursor-Modal

src/pages/disputes/disputeDetail/index.tsx, src/pages/disputes/disputeDetail/useDisputeDetail.tsx
=> TAS-2190/Category-Dispute-Detail

src/modules/userProfile/containers/editInfoOrg/index.tsx, src/modules/userProfile/containers/editInfoOrg/useEditInfoOrg.tsx, src/pages/orgProfile/index.tsx, src/pages/userProfile/index.tsx
=> TAS-2143/Fix-Website-Edit-Profile

src/modules/Jobs/components/jobDetailAbout/jobDetailAbout.module.scss, src/modules/Jobs/components/jobDetailDescription/jobDetailDescription.module.scss, src/modules/Jobs/components/jobDetailHeader/jobDetailHeader.module.scss, src/pages/jobs/detail/index.tsx, src/pages/jobs/detail/jobDetail.module.scss
=> TAS-2209/Fix-Messy-Layout-Job-Detail

src/modules/general/components/Accordion/index.module.scss, src/modules/general/components/Accordion/index.tsx, src/modules/general/components/Accordion/index.types.ts
=> refactor: accordion according to new design in preferences

src/index.scss, src/modules/Disputes/DisputesList/index.module.scss, src/modules/Disputes/DisputesList/index.tsx, src/modules/Disputes/InvitationsList/index.module.scss, src/modules/Disputes/InvitationsList/index.tsx, src/modules/credentials/credentialsList/credentialsList.module.scss, src/modules/credentials/credentialsList/index.tsx, src/modules/credentials/issuedList/index.tsx, src/modules/credentials/issuedList/issuedList.module.scss, src/modules/dispute/components/contributorDashboard/contributorDashboard.module.scss
=> TAS-2165/Scroll-Inside-Tables

src/modules/general/components/input/input.tsx
=> TAS-2200/Scrollable-Unit-Offer-Amount

src/modules/chats/components/chatDetailItem/chatDetailItem.module.scss
=> TAS-2211/Preserved-Words-Message

src/modules/general/components/Button/button.module.scss, src/modules/userProfile/containers/editImage/index.tsx
=> TAS-2234/Fix-Error-Delete-Photo-Button

src/modules/Jobs/components/JobListingCard/index.tsx, src/modules/userProfile/components/jobs/index.tsx, src/modules/userProfile/components/jobs/organization-jobs.module.scss, src/modules/userProfile/components/jobs/useOrganizationJobs.tsx, src/pages/orgProfile/useOrgProfile.tsx
**FIX in jobs tab (org profile):**
TODO:
=> TAS-2182/Fix-Jobs-Tab-Design

src/modules/Auth/containers/onboarding/Causes/index.tsx, src/modules/contract/components/contractDetailsSlider/index.tsx, src/modules/contract/components/contractDetailsSlider/useContractDetailsSlider.tsx, src/modules/general/components/avatar/avatar.tsx
=> TAS-2217-TAS-2219

src/modules/credentials/educationDetails/useEducationDetails.tsx, src/modules/credentials/experienceDetails/useExperienceDetails.tsx, src/modules/userProfile/containers/createUpdateCertificate/useCreateUpdateCertificate.tsx, src/modules/userProfile/containers/createUpdateEducation/useCreateUpdateEducation.tsx, src/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/modules/userProfile/containers/verifyEducationModal/useVerifyEducationModal.tsx, src/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx
=> TAS-2216/Descending-Year

src/core/router/router.blueprint.tsx, src/core/utils.tsx, src/modules/Search/components/FilterSlider/filtersReducer.ts, src/modules/Search/components/FilterSlider/index.tsx, src/modules/Search/components/FilterSlider/useFilterSlider.tsx, src/pages/search/useSearch.tsx
=> TAS-2144/people-search-filters

src/modules/credentials/educationDetails/index.tsx, src/modules/credentials/educationDetails/useEducationDetails.tsx, src/modules/credentials/experienceDetails/index.tsx, src/modules/credentials/experienceDetails/useExperienceDetails.tsx, src/modules/userProfile/containers/createUpdateCertificate/index.tsx, src/modules/userProfile/containers/createUpdateCertificate/useCreateUpdateCertificate.tsx, src/modules/userProfile/containers/createUpdateEducation/index.tsx, src/modules/userProfile/containers/createUpdateEducation/useCreateUpdateEducation.tsx, src/modules/userProfile/containers/createUpdateExperience/index.tsx, src/modules/userProfile/containers/createUpdateExperience/useCreateUpdateExperience.tsx, src/modules/userProfile/containers/verifyEducationModal/index.tsx, src/modules/userProfile/containers/verifyEducationModal/useVerifyEducationModal.tsx, src/modules/userProfile/containers/verifyExperience/index.tsx, src/modules/userProfile/containers/verifyExperience/useVerifyExperience.tsx
**This branch is for fixing some issues (hidden `placeholder`, max `menu height`, validation for more than `current date`, and wrong `day options` for each month) in:**
TODO:
=> TAS-2349/Fix-Date

src/constants/EVENTS_QUERIES.ts, src/core/api/auth/auth.api.ts, src/core/api/site/site.types.ts, src/core/router/router.blueprint.tsx, src/modules/Auth/containers/forgetPassword/EmailForm/useEmailForm.tsx, src/modules/Auth/containers/forgetPassword/OtpForm/useOtpForm.tsx, src/modules/Auth/containers/forgetPassword/PasswordForm/usePasswordForm.tsx, src/modules/Auth/containers/onboarding/ImageBio/useImageBio.tsx, src/modules/Auth/containers/signin/SignInForm/index.tsx, src/modules/Auth/containers/signin/SignInForm/useSignInForm.tsx, src/modules/Auth/containers/signup/EmailForm/index.tsx, src/modules/Auth/containers/signup/EmailForm/useEmailForm.tsx, src/modules/Events/TechSummit/index.module.scss, src/modules/Events/TechSummit/index.tsx, src/pages/Intro/index.tsx, src/pages/forget-password/resetCompleted.tsx, src/pages/oauth/google.tsx, src/pages/sign-in/index.tsx, src/pages/sign-up/Congrats/index.tsx, src/pages/sign-up/Email/index.tsx
**This branch is related to login/register with special event id**, includes:
TODO:
=> TAS-2290/TAS-2292/Tech4Impact-Sign(in-up)

cypress/e2e/authentication/sign-in.cy.ts, src/modules/Auth/containers/signin/SignInForm/index.tsx, src/modules/Events/TechSummit/index.module.scss, src/modules/Search/components/searchResultProfile/index.tsx, src/modules/general/components/profileCard/index.tsx, src/modules/userProfile/components/mainInfo/index.tsx, src/pages/Intro/index.tsx, src/pages/sign-up/Email/index.tsx, src/styles/constants/_primitives.scss
**This branch is for showing chip on:**
BUT also needs:
TODO:
=> TAS-2293/Events-Chip

src/modules/userProfile/components/jobs/useOrganizationJobs.tsx
=> TAS-1978/Fix-Mobile-Pagination-Jobs-Organization

src/modules/Jobs/jobCreate/containers/JobCreateForm/useJobCreateForm.tsx
=> TAS-387/Fix-Edit-Job

src/modules/chats/components/summaryCard/index.tsx
=> TAS-2515/Fix-Chats-Username

cypress/e2e/jobs/u-apply.cy.ts, package-lock.json, package.json, src/modules/userProfile/components/profileHeader/desktopHeader.tsx, src/modules/userProfile/components/profileHeader/index.tsx, src/modules/userProfile/components/profileHeader/useProfileHeader.tsx, src/modules/userProfile/containers/shareProfile/index.tsx, src/modules/userProfile/containers/shareProfile/index.types.ts, src/modules/userProfile/containers/shareProfile/shareProfile.module.scss, src/modules/userProfile/containers/shareProfile/useShareProfile.tsx
**This branch is related to sharing profile via link and QR code**
TODO:
=> TAS-2266/Share-Profile

src/modules/Jobs/components/jobDetailAbout/index.tsx, src/modules/Jobs/components/jobDetailHeader/index.tsx
=> TAS-2502/Fix-Closed-Job

src/modules/Search/components/searchResultProfile/index.tsx
=> TAS-2417/Skills-People-Card

src/modules/general/components/input/input.module.scss
=> TAS-2418/Word-Break-MultiLine-Input

src/modules/chats/components/chatDetailItem/chatDetailItem.module.scss, src/modules/feeds/createPostModal/index.module.scss, src/modules/feeds/repostModal/index.module.scss, src/modules/general/components/input/input.module.scss, src/pages/jobs/detail/applicants/applicant.tsx
**FIX** `word-break` for long texts:
=> TAS-2418/Word-Break

src/modules/general/components/stepperCard/index.tsx
=> TAS-2647/Experience-Education-Description-Format

src/core/api/users/users.api.ts, src/core/api/users/users.types.ts, src/modules/refer/referCard/index.tsx, src/modules/refer/referCard/useReferCard.tsx
=> TAS-2632/Referral-Email

src/modules/userProfile/containers/editInfo/editInfo.module.scss, src/modules/userProfile/containers/editInfo/index.tsx, src/modules/userProfile/containers/editInfoOrg/editInfo.module.scss, src/modules/userProfile/containers/editInfoOrg/index.tsx
=> TAS-2650/Safe-Top-Area-Edit-Profile

src/modules/credentials/issuedList/index.tsx, src/modules/credentials/issuedList/useIssuedList.tsx
=> TAS-1524/Claim-Credentials

src/pages/contracts/index.tsx
=> TAS-1071/Blury-Overlay

src/modules/userProfile/components/about/about.module.scss, src/modules/userProfile/components/about/certificate/certificates.tsx, src/modules/userProfile/components/about/certificate/useCertificates.types.tsx, src/modules/userProfile/components/about/education/educations.tsx, src/modules/userProfile/components/about/education/useEducation.tsx, src/modules/userProfile/components/about/experience/experience.tsx, src/modules/userProfile/components/about/experience/useExperience.tsx
**This branch is related to the limitation of some parts on `user profile`**, includes:
TODO:
=> TAS-2671/User-Profile-Limit

src/pages/disputes/disputeDetail/disputeDetail.module.scss, src/pages/disputes/disputeDetail/index.tsx
=> TAS-1505/Fix-Alert-Box-Dispute

android/app/src/main/AndroidManifest.xml, capacitor.config.ts, ios/App/App.xcodeproj/project.pbxproj, ios/App/App.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings, ios/App/App/AppDelegate.swift, ios/App/App/capacitor.config.json, ios/App/App/public/index.html, src/App.tsx, src/core/deepLinks.tsx, src/modules/layout/index.tsx, src/pages/oauth/google.tsx
=> Tas 2636/google login

src/core/translation/locales/en/services.json, src/core/translation/locales/jp/services.json, src/modules/Services/components/ServiceCard/index.module.scss, src/modules/Services/components/ServiceCard/index.tsx, src/modules/Services/components/ServiceCard/index.types.ts, src/modules/Services/components/ServiceDetailBox/index.tsx, src/modules/Services/components/ServiceOrderDetail/index.tsx, src/modules/Services/containers/ServiceCreateForm/index.tsx, src/modules/Services/containers/ServiceCreateForm/useServiceCreateForm.tsx, src/modules/Services/containers/ServicesList/index.tsx
=> TAS-2607/Fix-QA-Feedbacks

src/modules/Search/components/FilterSlider/index.tsx
=> fix: commented remote preference & location

src/modules/feeds/feedItem/index.tsx
=> TAS-3128/Redirect-Avatar-Feeds

src/core/api/site/site.api.ts, src/core/utils.tsx
=> TAS-3160/FIx-Jobs-Search

src/core/translation/locales/en/reviews.json, src/core/translation/locales/es/reviews.json, src/core/translation/locales/jp/reviews.json, src/core/translation/locales/kr/reviews.json, src/modules/Reviews/containers/ReviewsList/index.module.scss, src/modules/Reviews/containers/ReviewsList/index.tsx, src/pages/orgProfile/index.tsx, src/pages/orgProfile/useOrgProfile.tsx, src/pages/userProfile/index.tsx, src/pages/userProfile/useUserProfile.tsx
=> TAS-3211/Empty-Reviews-List

src/pages/orgProfile/useOrgProfile.tsx
=> TAS-3166/Fix-Preferences-Display

src/modules/layout/components/linksContainer/linksContainer.tsx
=> TAS-3126/Auto-Close-Navbar

src/core/time.ts
=> TAS-3482/Linkedin-Date

src/modules/chats/components/chatDetailItem/chatDetailItem.module.scss, src/modules/chats/components/chatDetailItem/index.tsx, src/modules/chats/components/sendMessage/index.module.scss, src/modules/chats/components/sendMessage/index.tsx, src/modules/general/components/input/input.module.scss, src/modules/general/components/input/input.tsx
https://github.com/user-attachments/assets/0ac4bf17-dcea-4cc0-8c10-0c8915f82cc3
https://github.com/user-attachments/assets/59b60600-eee8-4565-8772-19a1cc761ed5
=> TAS-3432/Chats-Improvement

src/core/utils.tsx, src/modules/userProfile/containers/editInfo/useEditInfo.tsx
=> TAS-3517/User-Edit-Profile-Issue

src/modules/chats/components/summaryCard/index.tsx, src/modules/general/components/avatarLabelGroup/index.tsx
=> TAS-3269/Long-Username-Chat

src/core/hooks/useSwitchLanguage.tsx, src/core/translation/i18n.ts, src/modules/settings/components/Language/useLanguage.tsx
=> TAS-4086/Fix-Default-Browser-Language
